### ISSUE TITLE
Get token automatically

### ISSUE THREAD

**Issue by elegaanz** [SkyLeite/funkwhale-cli#4]
Funkwhale provides an API for getting a token with a username/password couple, so it would be nice if it could be obtained automatically and saved by funkwhale-cli. You would just have to provide a username and password the first time you use it.

**Comment by SkyLeite** [comment]
- Store the token file with strict permissions (600), enforced by the program, at $HOME/.local/share/funkwhale-cli

- `login` command that generates the file, overwriting any previous ones with confirmation in interactive mode
